/// SyntaxKind.swift
/// Automatically generated by SyntaxGen. Do not edit!
///
/// Copyright 2017, The Silt Language Project.
///
/// This project is released under the MIT license, a copy of which is
/// available in the repository.
public enum SyntaxKind {
  case token
  case unknown
  case identifierList
  case qualifiedName
  case qualifiedNamePiece
  case moduleDecl
  case declList
  case openImportDecl
  case importDecl
  case dataDecl
  case typeIndices
  case typedParameterList
  case ascription
  case typedParameter
  case constructorList
  case constructorDecl
  case recordDecl
  case recordElementList
  case recordElement
  case fieldDecl
  case recordFieldAssignmentList
  case recordFieldAssignment
  case functionDecl
  case functionClauseList
  case functionClause
  case normalFunctionClause
  case withRuleFunctionClause
  case patternClauseList
  case typedParameterArrowExpr
  case basicExprListArrowExpr
  case lambdaExpr
  case quantifiedExpr
  case letExpr
  case applicationExpr
  case basicExpr
  case applicationExprList
  case bindingList
  case binding
  case namedBinding
  case typedBinding
  case basicExprList
  case namedBasicExpr
  case underscoreExpr
  case typeBasicExpr
  case parenthesizedExpr
  case recordExpr

  public var syntaxType: Syntax.Type {
    switch self {
    case .token: return TokenSyntax.self
    case .unknown: return Syntax.self
    case .identifierList: return IdentifierListSyntax.self
    case .qualifiedName: return QualifiedNameSyntax.self
    case .qualifiedNamePiece: return QualifiedNamePieceSyntax.self
    case .moduleDecl: return ModuleDeclSyntax.self
    case .declList: return DeclListSyntax.self
    case .openImportDecl: return OpenImportDeclSyntax.self
    case .importDecl: return ImportDeclSyntax.self
    case .dataDecl: return DataDeclSyntax.self
    case .typeIndices: return TypeIndicesSyntax.self
    case .typedParameterList: return TypedParameterListSyntax.self
    case .ascription: return AscriptionSyntax.self
    case .typedParameter: return TypedParameterSyntax.self
    case .constructorList: return ConstructorListSyntax.self
    case .constructorDecl: return ConstructorDeclSyntax.self
    case .recordDecl: return RecordDeclSyntax.self
    case .recordElementList: return RecordElementListSyntax.self
    case .recordElement: return RecordElementSyntax.self
    case .fieldDecl: return FieldDeclSyntax.self
    case .recordFieldAssignmentList: return RecordFieldAssignmentListSyntax.self
    case .recordFieldAssignment: return RecordFieldAssignmentSyntax.self
    case .functionDecl: return FunctionDeclSyntax.self
    case .functionClauseList: return FunctionClauseListSyntax.self
    case .functionClause: return FunctionClauseSyntax.self
    case .normalFunctionClause: return NormalFunctionClauseSyntax.self
    case .withRuleFunctionClause: return WithRuleFunctionClauseSyntax.self
    case .patternClauseList: return PatternClauseListSyntax.self
    case .typedParameterArrowExpr: return TypedParameterArrowExprSyntax.self
    case .basicExprListArrowExpr: return BasicExprListArrowExprSyntax.self
    case .lambdaExpr: return LambdaExprSyntax.self
    case .quantifiedExpr: return QuantifiedExprSyntax.self
    case .letExpr: return LetExprSyntax.self
    case .applicationExpr: return ApplicationExprSyntax.self
    case .basicExpr: return BasicExprSyntax.self
    case .applicationExprList: return ApplicationExprListSyntax.self
    case .bindingList: return BindingListSyntax.self
    case .binding: return BindingSyntax.self
    case .namedBinding: return NamedBindingSyntax.self
    case .typedBinding: return TypedBindingSyntax.self
    case .basicExprList: return BasicExprListSyntax.self
    case .namedBasicExpr: return NamedBasicExprSyntax.self
    case .underscoreExpr: return UnderscoreExprSyntax.self
    case .typeBasicExpr: return TypeBasicExprSyntax.self
    case .parenthesizedExpr: return ParenthesizedExprSyntax.self
    case .recordExpr: return RecordExprSyntax.self
    }
  }
}
