// SyntaxKind.swift
// Automatically generated by SyntaxGen. Do not edit!
//
// Copyright 2017, The Silt Language Project.
//
// This project is released under the MIT license, a copy of which is
// available in the repository.
public enum SyntaxKind {
  case token
  case unknown
  case funcApplicationExpr
  case lambdaExpr
  case parenExpr
  case integerLiteralExpr
  case parameterList
  case exprList

  public var syntaxType: Syntax.Type {
    switch self {
    case .token: return TokenSyntax.self
    case .unknown: return Syntax.self
    case .funcApplicationExpr: return FuncApplicationExprSyntax.self
    case .lambdaExpr: return LambdaExprSyntax.self
    case .parenExpr: return ParenExprSyntax.self
    case .integerLiteralExpr: return IntegerLiteralExprSyntax.self
    case .parameterList: return ParameterListSyntax.self
    case .exprList: return ExprListSyntax.self
    }
  }
}
